server:
  port: 8080

spring:
  application:
    name: spring-boot-dubbo-provider
  main:
    allow-bean-definition-overriding: true

  #  zipkin

  zipkin:
    base-url: http://10.7.92.76:9411
    service:
      name: spring-boot-dubbo-provider
  sleuth:
    sampler:
      probability: 1.0
    enabled: true

#  dubbo
dubbo:
  application:
    name: spring-boot-dubbo-provider
  registry:
    address: nacos://10.7.92.76:8848
    parameters:
      namespace: zdb
  provider:
    filter: tracing
  consumer:
    filter: tracing
  protocol:
    name: dubbo
    port: 20881


